# Session 1.2 : Pandas for Data Analysis

_Analytics Through Coding Autumn 2026_

---

You have already encountered pandas during the pre-course preparation.  
In this session, we will **refresh the core pandas skills that we need for analysis**, then focus on understanding, checking and selecting data before carrying out any analysis.

The aim is not to memorise every pandas command. Instead, we want to develop a reliable workflow for asking:

* What does this dataset contain?
* Is the data in the form I expect?
* Are there missing or unusual values?
* How can I select the observations I need?
* What simple summaries help me understand the data?

---

## Starting out

First, we import the packages that we will use.

By convention, pandas is imported as `pd` and NumPy as `np`.

In [2]:
import pandas as pd
import numpy as np

## Creating and reading data

A pandas **DataFrame** is a two-dimensional table made up of rows and columns.

We can create one manually, although in practice we will usually read data from a file.

<div class="alert alert-warning">
<b>Refresher.</b>
A DataFrame is similar to a spreadsheet table. Rows normally represent observations and columns represent variables.
</div>

### Exercise

Using the `sales` DataFrame above:

1. Display the column names.
2. Determine the number of rows and columns.
3. Display the data type of each column.

More often, DataFrames are created from data files such as **CSV (comma-separated values)** files using `pd.read_csv()`.

Let's import the wine reviews dataset that we will use throughout this session.

In [4]:
reviews = pd.read_csv("../Data/wine_reviews.csv", index_col = 0)

reviews = reviews.reset_index(drop=True)

reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83,5.0,Australia Other,South Eastern Australia,NaN,Joe Czerwinski,@JoeCz,Banrock Station 2006 Chardonnay (South Eastern...,Chardonnay,Banrock Station
1,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
2,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86,9.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Esperanza 2013 Estate Grown & Bottled Verdejo-...,Verdejo-Viura,Esperanza
3,US,This is the winery's best Nebula in years. Whi...,Nebula,87,29.0,California,Paso Robles,Central Coast,NaN,NaN,Midnight 2010 Nebula Cabernet Sauvignon (Paso ...,Cabernet Sauvignon,Midnight
4,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88,40.0,California,Anderson Valley,NaN,NaN,NaN,Harrington 2006 Wiley Vineyard Pinot Noir (And...,Pinot Noir,Harrington

## First look at a dataset

When you receive a new dataset, avoid immediately jumping into analysis.

A good first step is to understand its **shape, structure and variables**.

### Think about the data

Before continuing, ask yourself:

* What does one row represent?
* What does each column represent?
* Which variables are numerical?
* Which variables are categorical or text?
* Are any data types unexpected?

These questions help us understand what we can reasonably do with the data.

### Exercise

Use pandas to:

1. Display the first 10 rows.
2. Display the last 5 rows.
3. Determine the number of observations and variables.
4. Display the names of all variables.

In [10]:
display(reviews.head(10))
display(reviews.tail(5))

print(reviews.shape)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83,5.0,Australia Other,South Eastern Australia,NaN,Joe Czerwinski,@JoeCz,Banrock Station 2006 Chardonnay (South Eastern...,Chardonnay,Banrock Station
1,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
2,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86,9.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Esperanza 2013 Estate Grown & Bottled Verdejo-...,Verdejo-Viura,Esperanza
3,US,This is the winery's best Nebula in years. Whi...,Nebula,87,29.0,California,Paso Robles,Central Coast,NaN,NaN,Midnight 2010 Nebula Cabernet Sauvignon (Paso ...,Cabernet Sauvignon,Midnight
4,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88,40.0,California,Anderson Valley,NaN,NaN,NaN,Harrington 2006 Wiley Vineyard Pinot Noir (And...,Pinot Noir,Harrington
5,US,"An unabashedly rich and luscious wine, this co...",NaN,90,22.0,California,Sonoma County-Monterey County-Santa Barbara Co...,California Other,Jim Gordon,@gordone_cellars,Meiomi 2013 Chardonnay (Sonoma County-Monterey...,Chardonnay,Meiomi
6,US,"This opens with a pleasing toasty aroma, follo...",Five Faces,90,33.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Fullerton 2014 Five Faces Pinot Noir (Willamet...,Pinot Noir,Fullerton
7,Italy,"Made with 100% Chardonnay, this creamy sparkle...",Saten,89,35.0,Lombardy,Franciacorta,NaN,Kerin O’Keefe,@kerinokeefe,Lantieri de Paratico NV Saten Chardonnay (Fran...,Chardonnay,Lantieri de Paratico
8,US,"Here's a good, everyday Cab if you're looking ...",NaN,84,10.0,California,Central Coast,Central Coast,NaN,NaN,Cupcake 2005 Cabernet Sauvignon (Central Coast),Cabernet Sauvignon,Cupcake
9,France,"Made from low-yielding, 70-year-old vines, thi...",Clos du Château,92,21.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaine du Clos Gautier 2015 Clos du Château R...,Rosé,Domaine du Clos Gautier

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
58482,US,A solid effort from a dependable winery that u...,Winemaker's Reserve,88,35.0,California,Sonoma County,Sonoma,NaN,NaN,Château Souverain 1996 Winemaker's Reserve Cab...,Cabernet Sauvignon,Château Souverain
58483,Greece,"Crushed thyme, pine resin and lemon start this...",Retsina of Attica,86,9.0,Attica,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Kourtaki NV Retsina of Attica Savatiano (Attica),Savatiano,Kourtaki
58484,Italy,"Made from Negroamaro, this opens with aromas o...",NaN,87,15.0,Southern Italy,Salento,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Altemura 2016 Rosato (Salento),Rosato,Masseria Altemura
58485,US,"This big, bold wine has the taste profile of a...",Estate Mae's Block Ravazzi Vineyard,88,32.0,California,Mendocino,NaN,Jim Gordon,@gordone_cellars,Jaxon Keys 2013 Estate Mae's Block Ravazzi Vin...,Zinfandel,Jaxon Keys
58486,Spain,"Zingy and sort of floral on the nose, but fair...",Blanco,82,10.0,Central Spain,La Mancha,NaN,Michael Schachner,@wineschach,Finca Antigua 2006 Blanco Viura (La Mancha),Viura,Finca Antigua

(58487, 13)

## Selecting Data

Selecting data is one of the most common pandas operations.

We will focus on three common situations:

1. Selecting columns.
2. Selecting rows by position or label.
3. Selecting rows using conditions.

We will practise using the wine reviews DataFrame.

### 1. Selecting columns

A single column can be selected using square brackets.

In [11]:
reviews[["country" , "province" , "points" , "price"]]

         country         province  points  price
0      Australia  Australia Other      83    5.0
1         France     Rhône Valley      85   12.0
2          Spain   Northern Spain      86    9.0
3             US       California      87   29.0
4             US       California      88   40.0
...          ...              ...     ...    ...
58482         US       California      88   35.0
58483     Greece           Attica      86    9.0
58484      Italy   Southern Italy      87   15.0
58485         US       California      88   32.0
58486      Spain    Central Spain      82   10.0

[58487 rows x 4 columns]

Multiple columns can be selected by passing a list of column names.

### Exercise

Create a DataFrame called `wine_subset` containing only:

* `country`
* `province`
* `points`
* `price`

Display the first 10 rows.

In [13]:
wine_subset = reviews[["country" , "province" , "points" , "price"]]
wine_subset.head(10)

     country         province  points  price
0  Australia  Australia Other      83    5.0
1     France     Rhône Valley      85   12.0
2      Spain   Northern Spain      86    9.0
3         US       California      87   29.0
4         US       California      88   40.0
5         US       California      90   22.0
6         US           Oregon      90   33.0
7      Italy         Lombardy      89   35.0
8         US       California      84   10.0
9     France         Provence      92   21.0

### 2. Selecting rows with `loc` and `iloc`

`loc[]` selects using **labels**.

`iloc[]` selects using **positions**.

In [14]:
# Select rows with index labels 10, 750 and 1200
reviews.loc[[10 , 750 , 1200]]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
10,US,"Amidst cola and sassafras on the nose, there's...",White Hawk Vineyard,89,38.0,California,Santa Barbara County,Central Coast,Matt Kettmann,@mattkettmann,Deep Sea 2011 White Hawk Vineyard Syrah (Santa...,Syrah,Deep Sea
750,France,There's a green edge to this wine that struggl...,Le Dog de Jean Marc,84,11.0,Languedoc-Roussillon,Vin de Pays d'Oc,NaN,Lauren Buzzeo,@laurbuzz,Mont Tauch 2009 Le Dog de Jean Marc Merlot (Vi...,Merlot,Mont Tauch
1200,US,Full-bodied in apple and pineapple aromas at f...,Hybrid,81,10.0,California,Lodi,Central Valley,Virginie Boone,@vboone,Peltier 2012 Hybrid Chardonnay (Lodi),Chardonnay,Peltier

In [15]:
# Select the first 5 rows and first 4 columns by position
reviews.iloc[0:5, 0:4]

,country,description,designation,points
0,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83
1,France,"A soft, almost off dry wine that is full in th...",Réserve,85
2,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86
3,US,This is the winery's best Nebula in years. Whi...,Nebula,87
4,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88

<div class="alert alert-warning">
<b>Remember.</b>
<code>loc</code> works with labels and conditions.  
<code>iloc</code> works with numerical positions.
</div>

### Exercise

Create a sub-DataFrame containing the `country`, `province`, `region_1` and `region_2` columns for rows with index labels `10`, `750` and `1200`.

In [17]:
reviews.loc 
    [10 , 750 , 1200],
    ["country" , "province" , "region"]

IndentationError: unexpected indent (1863397338.py, line 2)

### 3. Selecting rows using conditions

Boolean conditions allow us to keep only observations that satisfy a rule.

In [18]:
reviews.loc[reviews["country" == "France"]]

KeyError: False

We can combine conditions using:

* `&` for **and**
* `|` for **or**

Each condition should be placed inside parentheses.

In [ ]:
reviwes.loc[(reviews["country"] == "France") & (reviews["points"])

`.isin()` is useful when we want to match several possible values.

In [19]:
reviews.loc[
    reviews["country"].isin["France" , "Italy"]]
]

SyntaxError: unmatched ']' (3733664315.py, line 3)

### Exercise

Create a DataFrame called `high_scoring_oceania` containing all wines that:

* have at least **95 points**; and
* come from **Australia or New Zealand**.

Keep only the columns `country`, `province`, `points`, `price` and `title`.

Display the first 10 rows.

In [ ]:
high_scoring_oceania = reviews.loc[
    (reviews["points"] == 95) &
    (reviews["country".isin)]
]

## Inspecting Data Quality

Before analysing a dataset, we should check whether the data look reliable.

Useful questions include:

* Are values missing?
* Are there duplicated rows?
* Do numerical values have plausible ranges?
* How many unique values does each variable contain?
* Are the data types appropriate?

These checks do not automatically tell us what to do, but they help us identify potential problems.

In [1]:
# How many missing values are in each column?
reviews.isna()

NameError: name 'reviews' is not defined

In [ ]:
# What proportion of each column is missing?
reviews.doplicated().sum()

In [ ]:
# How many completely duplicated rows are there?
reviews.unique

In [ ]:
# How many unique values are in each column?
reviews.describe()

In [ ]:
# Quick numerical summary

<div class="alert alert-warning">
<b>Important.</b>
Finding missing values does not automatically mean that we should drop them or replace them.

Before changing the data, ask:

<ul>
<li>Why might the value be missing?</li>
<li>How much data would we lose by dropping rows?</li>
<li>Would replacing the value introduce unrealistic information?</li>
<li>Could the missingness itself be informative?</li>
</ul>
</div>

### Exercise

Investigate missing values in the `price` column.

1. Count how many prices are missing.
2. Calculate the percentage of observations with a missing price.
3. Create a DataFrame called `missing_price` containing only rows where price is missing.
4. Display the first five rows.

In [ ]:
# 1
reviews["price"].isna().sum()

NameError: name 'reviews' is not defined

## Summary Functions

Summary functions allow us to quickly describe and understand a dataset.

Common examples include:

* `.mean()`
* `.median()`
* `.min()`
* `.max()`
* `.sum()`
* `.value_counts()`
* `.unique()`
* `.describe()`

In [ ]:
reviews["country"]

### Exercise

Use pandas to answer the following:

1. What is the highest number of points awarded to a wine?
2. What is the lowest number of points?
3. What is the median wine price?
4. Which five countries have the largest number of reviews?

## Mini Challenge

You have been asked to take a first look at **highly rated wines**.

Create a DataFrame containing wines with at least **95 points** and investigate it.

Using pandas:

1. Create a DataFrame called `high_rated` containing wines with at least 95 points.
2. Determine how many wines meet this condition.
3. Determine which countries are represented.
4. Check how many of these wines have a missing price.
5. Calculate the mean and median price.
6. Display the 10 most expensive highly rated wines using only:
   * `country`
   * `title`
   * `points`
   * `price`

As you work, think about what else you might want to know before drawing conclusions from this subset.

In [ ]:
high-rated

## All Done!

In this session we refreshed how to:

* read a dataset into pandas;
* inspect its structure;
* select columns and rows;
* filter observations using conditions;
* identify missing values and duplicates;
* calculate simple summary statistics;
* check data quality before analysis.

The important habit is to **understand and validate the data before trying to answer an analytical question**.

In the next part of the course, we will build on these foundations to transform, aggregate, reshape and combine datasets.